# SPDX-FileCopyrightText: 2024 2024 Dan Anglin <d.n.i.anglin@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

---
run:
  concurrency: 2
  timeout: 1m
  issues-exit-code: 1
  tests: true

output:
  formats: colored-line-number
  print-issues-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  depguard:
    rules:
      main:
        files:
        - $all
        allow:
        - $gostd
        - codeflow.dananglin.me.uk/apollo/beacon
        - github.com/golang-jwt/jwt/v5
  lll:
    line-length: 140

linters:
  enable-all: true
  # disable:
  fast: false
